[package]
name = "causal_ml"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.17.2"
ndarray-stats = "0.7.0"
rand = "0.10.3"

[[bin]]
name = "unbiased_estimators"
path = "error/estimation_error/unbiased_estimators.rs"

[[bin]]
name = "prediction_error"
path = "error/prediction_error/prediction_error.rs"
